### ISSUE TITLE
www-data has no shell on jessie

### ISSUE THREAD

**Issue by src386** [julienmalik/baikal_ynh#10]
Hi,

When I click on "Baikal" in my Yunohost portal I get this : 

    Incomplete installation
    Baïkal dependencies have not been installed. Please, execute "composer install" in the folder where you installed Baïkal.

According to installation log, this is a problem with composer : 

    + sudo su -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/var/www/baikal' www-data
    This account is currently not available.
    + sudo su -c 'cd /var/www/baikal && php composer.phar install' www-data
    This account is currently not available.

The reason seems to be www-data default shell : 
* On wheezy /bin/sh
* On Jessie /usr/sbin/nologin

Regards

**Comment by src386** [comment]
I suggest adding this : 
    -s /bin/sh

For these 2 command lines...

**Comment by julienmalik** [comment]
we should probably not run the installation as www-data but create a specific system user 'baikal', and probably remove the login shell after installation if it is not necessary

**Comment by julienmalik** [comment]
Same to do for upgrade script : https://github.com/julienmalik/baikal_ynh/commit/c2386b95552fec30ac06a446ac7a67d61a290b51
