### ISSUE TITLE
Configuration carddav roundcube

### ISSUE THREAD

**Issue by paoesco** [julienmalik/baikal_ynh#5]
Bonjour,

quand on installe Baikal après avoir installé Roundcube, le carddav dans Roundcube n'est pas configuré pour Baikal.
Pour le confort, il faudrait que le package Baikal soit capable de détecter si Roundcube est déjà installé et mette à jour automatiquement la configuration Roundcube.

Bonne journée

**Comment by julienmalik** [comment]
C'est intentionnel, pour le moment nous évitons ce genre de réaction en chaine.
Mais rien n'est figé dans le marbre.

**Comment by paoesco** [comment]
C'est dommage, RoundCube le fait bien lui, de détecter le serveur Baïkal.

(Code du script d'installation de roundcube)

# Install rcmcarddav if baikal is detected
sudo yunohost app list -f baikal --json | grep '"installed": true'
if [ "$?" -eq 0 ]; then
echo "Detected Baikal"

===========================
Yunohost automatise déjà beaucoup de choses et je trouve ça bien de pouvoir installer  les packages dans n'importe quel ordre.

Une autre possibilité serait d'ajouter un message dans la console d'administration à la fin de l'installation de Baïkal en précisant qu'il est nécessaire de réinstaller le webmail pour une configuration automatique.
