### ISSUE TITLE
Configuration of timezone

### ISSUE THREAD

**Issue by JocelynDelalande** [julienmalik/baikal_ynh#6]
I just installed baikal and it seems that it does not set the baikal timezone (It's set to africa/abidjan, which seems to be the default).

Could easily be guessed from underlying system.

**Comment by julienmalik** [comment]
see https://github.com/julienmalik/baikal_ynh/blob/master/scripts/install#L32

what does ```cat /etc/timezone``` returns on your system ?

**Comment by JocelynDelalande** [comment]
> what does cat /etc/timezone returns on your system ?

Europe/Paris

I admit that I don't understand. I will try on a fresh install to see what happens.
