### ISSUE TITLE
Incomplete Install on fresh install and latest yunohost

### ISSUE THREAD

**Issue by Vey** [julienmalik/baikal_ynh#7]
After a fresh yunohost install on a debian 8 based dedicated server, I installed baikal, everything seemed fine.

When I access baikal's URL (default : /baikal) I get:
> Incomplete installation
Baïkal dependencies have not been installed. Please, execute "composer install" in the folder where you installed Baïkal. 

So I did
> cd /var/www/baikal
composer install

and got " composer - unknown command"

Application was succesfully removed using webadmin panel inspite of an error message stating that "manifest.json was not found"

Let me know if you need any additionnal information

**Comment by s0r00t** [comment]
Install composer and try to run it again.

**Comment by julienmalik** [comment]
Vey : composer should have done its work at install time.
Can you uninstall baikal and reinstall again ? then paste here the installation logs (hiding the domain/password when appropriate).

Thanks

**Comment by Vey** [comment]
Hi, 

First, my apologies for the delay and thank you for your time s0r00t & julienmalik. 

Then, just in case, I started all over again:
- install debian 8 & sudo
- install yunohost & postinstall:
"Attention : dnsmasq ne semble pas Ãªtre installÃ©, veuillez lancer 'apt-get remove bind9 && apt-get install dnsmasq'
Failed to restart dnsmasq.service: Unit dnsmasq.service failed to load: No such file or directory.
SuccÃ¨s ! Domaine crÃ©Ã© avec succÃ¨s
Attention : Fichier de zone DNS introuvable pour le domaine
SuccÃ¨s ! Domaine principal modifiÃ© avec succÃ¨s
...
Erreur : Aucun pÃ©riphÃ©rique compatible UPnP trouvÃ©
..."
- apt-get remove bind9 && apt-get install dnsmasq (states error about yunohost-config dependency)
- connect to admin panel / firewall (UPnP port 5353 is down (X). Everything else is fine)
- create first user 
- install baikal with no errors stated
- connect to baikal & get:"
Incomplete installation
Baïkal dependencies have not been installed. Please, execute "composer install" in the folder where you installed Baïkal."
- connect to ssh & cd /var/www/baikal 
- composer install & get: "-bash: composer: command not found"
- desinstall app from admin panel (no errors) & run install from ssh:"
yunohost app install baikal

TÃ©lÃ©chargement...
Extraction...
TerminÃ©.
Choose a domain for baikal : tru.eu
Choose a path for baikal (default: /baikal) :
Choose a password for baikal admin : mdpbaikal
ExÃ©cution du script...
 domain=tru.eu
 path=/baikal
 password=mdpbaikal
 sudo yunohost app checkurl tru.eu/baikal -a baikal
 [[ ! 0 -eq 0 ]]
 sudo apt-get update
Atteint http://repo.yunohost.org megusta InRelease
Atteint http://debian.mirrors.ovh.net jessie InRelease
Atteint http://debian.mirrors.ovh.net jessie-updates InRelease
Atteint http://debian.mirrors.ovh.net jessie-backports InRelease
Atteint http://security.debian.org jessie/updates InRelease
Atteint http://repo.yunohost.org megusta/main amd64 Packages
Atteint http://debian.mirrors.ovh.net jessie/main Sources
Atteint http://debian.mirrors.ovh.net jessie/main amd64 Packages
Atteint http://debian.mirrors.ovh.net jessie/main Translation-fr
Atteint http://debian.mirrors.ovh.net jessie/main Translation-en
Ign http://repo.yunohost.org megusta/main Translation-fr_FR
Ign http://repo.yunohost.org megusta/main Translation-fr
Ign http://repo.yunohost.org megusta/main Translation-en
Atteint http://debian.mirrors.ovh.net jessie-updates/main Sources
RÃ©ception deÂ : 1 http://debian.mirrors.ovh.net jessie-updates/main amd64 Packages/DiffIndex [367 B]
RÃ©ception deÂ : 2 http://debian.mirrors.ovh.net jessie-updates/main Translation-en/DiffIndex [229 B]
RÃ©ception deÂ : 3 http://debian.mirrors.ovh.net jessie-backports/main Sources/DiffIndex [3 955 B]
RÃ©ception deÂ : 4 http://debian.mirrors.ovh.net jessie-backports/main amd64 Packages/DiffIndex [3 265 B]
RÃ©ception deÂ : 5 http://debian.mirrors.ovh.net jessie-backports/main Translation-en/DiffIndex [2 299 B]
Atteint http://security.debian.org jessie/updates/main Sources
Atteint http://security.debian.org jessie/updates/main amd64 Packages
Atteint http://security.debian.org jessie/updates/main Translation-en
10,1 ko rÃ©ceptionnÃ©s en 6s (1 641 o/s)
Lecture des listes de paquetsâ¦
 sudo apt-get install -y php5-cli
Lecture des listes de paquetsâ¦
Construction de l'arbre des dÃ©pendancesâ¦
Lecture des informations d'Ã©tatâ¦
php5-cli est dÃ©jÃ  la plus rÃ©cente version disponible.
0 mis Ã  jour, 0 nouvellement installÃ©s, 0 Ã  enlever et 0 non mis Ã  jour.
 final_path=/var/www/baikal
 sudo mkdir -p /var/www/baikal
 sudo cp -a ../sources/ChangeLog.md ../sources/composer.json ../sources/Core ../sources/html ../sources/INSTALL.md ../sources/LICENSE.txt ../sources/README.md ../sources/Specific ../sources/TROUBLESHOOTING.md ../sources/UPGRADE.md /var/www/baikal
 sudo chown -R www-data: /var/www/baikal
 sudo su -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/var/www/baikal' www-data
This account is currently not available.
 sudo su -c 'cd /var/www/baikal && php composer.phar install' www-data
This account is currently not available.
 sudo rm /var/www/baikal/composer.json
 dd if=/dev/urandom bs=1 count=200
 sed -n 's/\(.\{24\}\).*/\1/p'
 tr -c -d '[A-Za-z0-9]'
 db_pwd='npJJfad2ZK4]47teSN9GF8S0'
 db_user=baikal
 readlink -e ../sources/Core/Resources/Db/MySQL/db.sql
 sudo yunohost app initdb baikal -p 'npJJfad2ZK4]47teSN9GF8S0' -s /var/cache/yunohost/from_file/baikal_ynh-00bec35ca8f9e0c37093cb3ac7b232ed1c505e1b/sources/Core/Resources/Db/MySQL/db.sql
SuccÃ¨s ! Base de donnÃ©e MySQL initialisÃ©e avec succÃ¨s
 sudo yunohost app setting baikal mysqlpwd -v 'npJJfad2ZK4]47teSN9GF8S0'
 cat /etc/timezone
 sed -i s@YNH_TIMEZONE@Europe/Paris@g ../conf/config.php
 echo -n admin:BaikalDAV:mdpbaikal
 md5sum
 cut -d ' ' -f 1
 sed -i s@YNH_ADMIN_PASSWORDHASH@30a65f524ec3217f9fea636f0f982a92@g ../conf/config.php
 sudo yunohost app setting baikal password -v mdpbaikal
 sed -i s@YNH_LOCATION@/baikal@g ../conf/config.system.php
 sed -i s@YNH_DBNAME@baikal@g ../conf/config.system.php
 sed -i s@YNH_DBUSER@baikal@g ../conf/config.system.php
 sed -i 's@YNH_DBPWD@npJJfad2ZK4]47teSN9GF8S0@g' ../conf/config.system.php
 dd if=/dev/urandom bs=1 count=200
 tr -c -d A-Za-z0-9
 sed -n 's/\(.\{32\}\).*/\1/p'
 encrypt_key=2zPkcB9BIFXJjYgb7P8WV6xs5lTvsYms
 sudo yunohost app setting baikal encrypt_key -v 2zPkcB9BIFXJjYgb7P8WV6xs5lTvsYms
 sed -i s@YNH_ENCRYPTKEY@2zPkcB9BIFXJjYgb7P8WV6xs5lTvsYms@g ../conf/config.system.php
 sudo cp ../conf/config.php /var/www/baikal/Specific
 sudo cp ../conf/config.system.php /var/www/baikal/Specific
 sudo chown -R root: /var/www/baikal
 sudo chown -R www-data: /var/www/baikal/Specific
 sudo find /var/www/baikal -type f
 xargs sudo chmod 644
 sudo find /var/www/baikal -type d
 xargs sudo chmod 755
 sed -i s@PATHTOCHANGE@/baikal@g ../conf/nginx.conf
 sed -i s@ALIASTOCHANGE@/var/www/baikal/html@g ../conf/nginx.conf
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/tru.eu.d/baikal.conf
 sudo chown root: /etc/nginx/conf.d/tru.eu.d/baikal.conf
 sudo chmod 600 /etc/nginx/conf.d/tru.eu.d/baikal.conf
 sudo service nginx reload
Failed to open /dev/tty: Aucun pÃ©riphÃ©rique ou adresse
 sudo yunohost app setting baikal skipped_uris -v /
 sudo yunohost app ssowatconf
SuccÃ¨s ! Configuration de SSOwat gÃ©nÃ©rÃ©e avec succÃ¨s
SuccÃ¨s ! Configuration de SSOwat gÃ©nÃ©rÃ©e avec succÃ¨s
SuccÃ¨s ! Installation terminÃ©e

**Comment by julienmalik** [comment]
Ah ! the issue is that www-data user does not have a shell on jessie (contrary to wheezy).

Run the following command as admin : 
```
sudo usermod -s /bin/bash www-data
```
and then reinstall again. It should work.

**Comment by Vey** [comment]
...and it did...! \o/

Thank you for your time.
