### ISSUE TITLE
403 Forbidden when on a subdomain

### ISSUE THREAD

**Issue by s0r00t** [julienmalik/baikal_ynh#8]
Test case : 
-Create another subdomain (here, baikal.domain.tld)
-Install Baikal on it

Expected : "Baikal is running allright."
Results : 403 Forbidden

[This issue also happens with AgenDAV.](https://github.com/julienmalik/agendav_ynh/issues/12)

**Comment by stevenroose** [comment]
Is this being looked at?

**Comment by julienmalik** [comment]
if you access baikal.domain.tld/ (with an ending "/"), what happens ?

**Comment by julienmalik** [comment]
OK confirmed. ending "/" does not help

**Comment by julienmalik** [comment]
Closed by https://github.com/julienmalik/baikal_ynh/commit/86ab487397d27848c637ac3a1950dfc76271eb74
